name: Packer Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Setup Packer
      uses: hashicorp/setup-packer@v3
      with:
        packer_version: 'latest'

    - name: Initialize Packer
      run: packer init .

    - name: Validate Packer Configuration
      run: packer validate packer.pkr.hcl

    - name: Build Docker Image with Packer
      run: packer build packer.pkr.hcl

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Push Docker Image
      run: |   
        docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/rushiks3cloudhub/my-docker-image:latest

    - name: Logout from Azure
      run: docker logout ${{ secrets.REGISTRY_NAME }}
