name: Docker Build CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t my-react-app:latest .
