name: Linux_Container_Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: choice
        required: true
        options:
          - dev
        default: dev

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      acr_login_server: ${{ steps.tf_outputs.outputs.acr_login_server }}

    env:
      ARM_CLIENT_ID:       ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
      ARM_CLIENT_SECRET:   ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
      ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
      ARM_TENANT_ID:       ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./build-artifacts/acr

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./build-artifacts/acr

      - name: Get Terraform Outputs
        id: tf_outputs
        run: |
          echo "acr_login_server=$(terraform output -raw acr_login_server)" >> $GITHUB_OUTPUT
          echo "acr_admin_username=$(terraform output -raw acr_admin_username)" >> $GITHUB_OUTPUT
          echo "acr_admin_password=$(terraform output -raw acr_admin_password)" >> $GITHUB_OUTPUT
        working-directory: ./build-artifacts/acr

      - name: Docker Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.tf_outputs.outputs.acr_login_server }}
          username: ${{ steps.tf_outputs.outputs.acr_admin_username }}
          password: ${{ steps.tf_outputs.outputs.acr_admin_password }}

      - name: Docker Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ steps.tf_outputs.outputs.acr_login_server }}/sampleapp:${{ github.sha }} \
                       -t padmesh28/mews:${{ github.sha }} ./build-artifacts

      - name: Push Docker Image to ACR
        run: |
          docker push ${{ steps.tf_outputs.outputs.acr_login_server }}/sampleapp:${{ github.sha }}

      - name: Push Docker Image to Docker Hub
        run: |
          docker push padmesh28/mews:${{ github.sha }}

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event.inputs.environment == 'dev' }}

    env:
      ARM_CLIENT_ID:       ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
      ARM_CLIENT_SECRET:   ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
      ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
      ARM_TENANT_ID:       ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init (dev)
        run: terraform init
        working-directory: ./environments/dev

      - name: Terraform Plan (dev)
        run: terraform plan -var="image_tag=${{ github.sha }}" -var="acr_login_server=${{ needs.build.outputs.acr_login_server }}" -out=tfplan
        working-directory: ./environments/dev

      - name: Terraform Apply (dev)
        run: terraform apply tfplan
        working-directory: ./environments/dev
