name: Linux_Container_Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # ✅ Login to Azure using service principal (via AZURE_CREDENTIALS secret)
      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Debug working directory
        run: |
          pwd
          ls -R

      # ✅ Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      # ✅ Run Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: ./acr

      # ✅ Run Terraform Apply (provisions ACR with admin enabled)
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./acr

      # ✅ Get ACR outputs from Terraform (login server, user, pass)
      - name: Get Terraform Outputs
        id: tf_outputs
        run: |
          echo "acr_login_server=$(terraform output -raw acr_login_server)" >> $GITHUB_OUTPUT
          echo "acr_admin_username=$(terraform output -raw acr_admin_username)" >> $GITHUB_OUTPUT
          echo "acr_admin_password=$(terraform output -raw acr_admin_password)" >> $GITHUB_OUTPUT
        working-directory: ./acr

      # ✅ Login to ACR using credentials from Terraform output
      - name: Docker Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.tf_outputs.outputs.acr_login_server }}
          username: ${{ steps.tf_outputs.outputs.acr_admin_username }}
          password: ${{ steps.tf_outputs.outputs.acr_admin_password }}

      # ✅ Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ steps.tf_outputs.outputs.acr_login_server }}/sampleapp:${{ github.sha }} .

      # ✅ Push Docker image to ACR
      - name: Push Docker Image
        run: |
          docker push ${{ steps.tf_outputs.outputs.acr_login_server }}/sampleapp:${{ github.sha }}
