name: Terraform ACR and Docker CI

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: mews-platform-test
  IMAGE_TAG: ${{ github.sha }}

jobs:
  terraform_acr:
    name: Terraform Deploy ACR
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: build/acr   # <- corrected working directory

    outputs:
      acr_login_server: ${{ steps.tf_outputs.outputs.acr_login_server }}
      acr_admin_username: ${{ steps.tf_outputs.outputs.acr_admin_username }}
      acr_admin_password: ${{ steps.tf_outputs.outputs.acr_admin_password }}

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Capture Terraform Outputs
        id: tf_outputs
        run: |
          echo "acr_login_server=$(terraform output -raw acr_login_server)" >> $GITHUB_OUTPUT
          echo "acr_admin_username=$(terraform output -raw acr_admin_username)" >> $GITHUB_OUTPUT
          echo "acr_admin_password=$(terraform output -raw acr_admin_password)" >> $GITHUB_OUTPUT

  docker_build_push:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    needs: terraform_acr

    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ needs.terraform_acr.outputs.acr_login_server }}
          username: ${{ needs.terraform_acr.outputs.acr_admin_username }}
          password: ${{ needs.terraform_acr.outputs.acr_admin_password }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ needs.terraform_acr.outputs.acr_login_server }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Push Docker Image to ACR
        run: |
          docker push ${{ needs.terraform_acr.outputs.acr_login_server }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
